server:
  servlet:
    context-path: /rabbit-consumer
  port: 8081
spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/consumer?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: xxx
    password: xxx
    druid:
      initial-size: 5
      max-active: 200
      min-idle: 20
      max-wait: 30000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: select 1
      time-between-eviction-runs-millis: 60000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  # rabbitmq
  rabbitmq:
    addresses: xxx:5672
    username: admin
    password: xxx
    virtual-host: /
    user:
      user-topic-exchange: USER_TOPIC_EXCHANGE
      user-queue : USER_QUEUE
      routing-key1 : user.*
